[package]
name = "gs_bmc_encoder"
version = "1.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "gs_bmc_encoder"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.24.2"
